spring.application.name=tui
supabase.url=${SUPABASE_URL:https://coxctlozpgcmzedaocff.supabase.co}
supabase.key=${SUPABASE_KEY:sb_publishable_8cIJQo-it7j3DuZBfNJo-A_VtruTOZH}
spring.shell.interactive.enabled=false
spring.main.web-application-type=none